import "@/src/shared/styles";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeScript } from "@/src/shared/components/ThemeScript";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Keywith",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <ThemeScript />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
